### ISSUE TITLE
请教：要读日K线，如何调用呢？

### ISSUE THREAD

**Issue by Leadrive** [cyclegen-community/tdx-go#2]
cmd/main.go 可以跑，能否说说如何读日K线，谢谢！

**Comment by tonothing** [comment]
将[pytdx - parser](https://github.com/rainx/pytdx/tree/master/pytdx/parser)内的结构体分析按照[tdx-go - proto](https://github.com/cyclegen/tdx-go/blob/master/proto/v1/get_security_list.go)的方式解析，然后调用即可
